wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 64
dropout:
  value: 0.1
epochs:
  value: 20
filter_sizing:
  value: 10
learning_rate:
  value: 0.0001
mean_pool:
  value: 15
receptive_field:
  value: 75
