wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 64
dropout:
  value: 0.2
epochs:
  value: 10
filter_sizing:
  value: 30
learning_rate:
  value: 0.001
mean_pool:
  value: 50
receptive_field:
  value: 75
