wandb_version: 1

D:
  desc: null
  value:
    value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1652088133
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.16
      8:
      - 2
      - 3
      - 5
activation_type:
  desc: null
  value:
    value: elu
batch_size:
  desc: null
  value:
    value: 256
dropout:
  desc: null
  value:
    value: 0.4
epochs:
  desc: null
  value:
    value: 30
filter_sizing:
  desc: null
  value:
    value: 8
learning_rate:
  desc: null
  value:
    value: 0.001
mean_pool:
  desc: null
  value:
    value: 8
network:
  desc: null
  value:
    value: EEGNET
receptive_field:
  desc: null
  value:
    value: 64
seed:
  desc: null
  value:
    value: 42
test_subject:
  desc: null
  value:
    value:
    - X01
val_subjects:
  desc: null
  value:
    value:
    - X04
    - X06
