wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 25
filter_sizing:
  value: 8
learning_rate:
  value: 0.005
mean_pool:
  value: 15
receptive_field:
  value: 64
seed:
  value: 42
