wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 128
dropout:
  value: 0.2
epochs:
  value: 3
filter_sizings:
  value: 10
learning_rate:
  value: 0.01
mean_pools:
  value: 15
receptive_fields:
  value: 75
