wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 64
dropout:
  value: 0.2
epochs:
  value: 20
filter_sizing:
  value: 10
learning_rate:
  value: 0.01
mean_pool:
  value: 15
receptive_field:
  value: 50
