wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 32
dropout:
  value: 0.2
epochs:
  value: 1
filter_sizings:
  value: 20
learning_rate:
  value: 0.0001
mean_pools:
  value: 50
receptive_fields:
  value: 75
