wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 256
dropout:
  value: 0.25
epochs:
  value: 30
filter_sizing:
  value: 20
learning_rate:
  value: 0.001
mean_pool:
  value: 25
network:
  value: CNN
receptive_field:
  value: 50
seed:
  value: 42
val_subjects:
  value:
  - X04
  - X06
