wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 256
dropout:
  value: 0.25
epochs:
  value: 30
filter_sizing:
  value: 10
learning_rate:
  value: 0.005
mean_pool:
  value: 25
network:
  value: CNN
receptive_field:
  value: 25
seed:
  value: 42
val_subjects:
  value:
  - X04
  - X06
