wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1651829143
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      4: 3.9.7
      5: 0.12.16
      8:
      - 2
      - 3
      - 5
batch_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 25
filter_sizing:
  desc: null
  value: 8
kernel_sizes:
  desc: null
  value:
  - 256
  - 128
  - 64
learning_rate:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 42
