wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 32
dropout:
  value: 0.2
epochs:
  value: 10
filter_sizing:
  value: 40
learning_rate:
  value: 0.001
mean_pool:
  value: 25
receptive_field:
  value: 25
