wandb_version: 1

D:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1651838508
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      4: 3.9.7
      5: 0.12.16
      8:
      - 2
      - 3
      - 5
activation_type:
  desc: null
  value: elu
batch_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 1
filter_sizing:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.005
mean_pool:
  desc: null
  value: 8
receptive_field:
  desc: null
  value: 64
seed:
  desc: null
  value: 42
