wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 128
dropout:
  value: 0.2
epochs:
  value: 20
filter_sizing:
  value: 10
learning_rate:
  value: 0.001
mean_pool:
  value: 15
receptive_field:
  value: 50
seed:
  value: 42
