wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 32
dropout:
  value: 0.1
epochs:
  value: 1
filter_sizing:
  value: 10
learning_rate:
  value: 0.0001
mean_pool:
  value: 50
receptive_field:
  value: 50
