wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 25
filter_sizing:
  value: 20
learning_rate:
  value: 0.01
mean_pool:
  value: 15
receptive_field:
  value: 50
seed:
  value: 42
