wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 256
dropout:
  value: 0.3
epochs:
  value: 25
filter_sizing:
  value: 40
learning_rate:
  value: 0.01
mean_pool:
  value: 25
receptive_field:
  value: 75
seed:
  value: 42
