wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 256
dropout:
  value: 0.1
epochs:
  value: 25
filter_sizing:
  value: 10
learning_rate:
  value: 0.01
mean_pool:
  value: 25
receptive_field:
  value: 25
seed:
  value: 42
