wandb_version: 1

activation_type:
  value: elu
batch_size:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 25
filter_sizing:
  value: 30
learning_rate:
  value: 0.001
mean_pool:
  value: 50
receptive_field:
  value: 50
seed:
  value: 42
