wandb_version: 1

batch_size:
  value: 256
dropout:
  value: 0.2
epochs:
  value: 25
filter_sizing:
  value: 8
kernel_sizes:
  value:
  - 256
  - 128
  - 64
learning_rate:
  value: 0.001
seed:
  value: 42
