wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1651745150
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.9.7
      5: 0.12.16
      8:
      - 2
      - 3
      - 5
activation_type:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 1
filter_sizing:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.001
mean_pool:
  desc: null
  value: 15
receptive_field:
  desc: null
  value: 75
