wandb_version: 1

activation_type:
  value: relu
batch_size:
  value: 128
dropout:
  value: 0.3
epochs:
  value: 1
filter_sizing:
  value: 30
learning_rate:
  value: 0.001
mean_pool:
  value: 15
receptive_field:
  value: 75
